### ISSUE TITLE
[Python error]

### ISSUE THREAD

**Issue by marsofearth** [eswright/cgdi-qgis-services#29]
Python Error:
When loading any layer from the list.

QGIS 3.10 - MacOS 10.14.6

`2019-11-14T20:57:37     WARNING    Traceback (most recent call last):               File "/Users/marsofearth/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CanadianWebServices/canadian_web_services.py", line 137, in saveLayers               check = config["qgis"][base_settings+"url"] # Checks if the service has already been added               File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/configparser.py", line 958, in __getitem__               raise KeyError(key)              KeyError: 'qgis'                            During handling of the above exception, another exception occurred:                            Traceback (most recent call last):               File "/Users/marsofearth/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CanadianWebServices/canadian_web_services.py", line 574, in loadWebService               saveLayers(name,service_url[:-35],servType)               File "/Users/marsofearth/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CanadianWebServices/canadian_web_services.py", line 141, in saveLayers               config["qgis"][settings[i]] = settings_ans[i]               File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/configparser.py", line 958, in __getitem__               raise KeyError(key)              KeyError: 'qgis'`

**Comment by sachasmart** [comment]
Any updates with this? This error occurs when I attempt to load a map service. 

urllib.error.URLError: 
Traceback (most recent call last):
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

**Comment by prushforth** [comment]
I don't know if this relates to the issue raised here, but Google searches on the last error message seem to indicate that's a [possibility](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate).  

On the [download page for MacOS Python](https://www.python.org/downloads/release/python-376/), it says: "Please carefully read the Important Information displayed during installation for information about SSL/TLS certificate validation and the Install Certificates.command. Changed in 3.7.4 OpenSSL has been updated from 1.1.0 to 1.1.1."

I don't have MacOS, so I can't test it specifically.  I do confirm that I encounter the same issue as you when trying to access https services from the plugin.  However "http" service URLS load successfully.
